### ISSUE TITLE
Work with minSDK 22

### ISSUE THREAD

**Issue by MKevin3** [RotBolt/Flaker#75]
It appears the minimum SDK is 24 and this may be due to sql delight. I got very unhelpful error messages from AS trying to use it until I finally figured out it was a minimum SDK issue.

I know 22 is just not fun be we have to be there due to old specialized hardware.

Would love to use the project but I really needed to test crappy network so I wrote an OKHTTP interceptor that put in a 1s delay and was able to replicate and fix the code issue I had that I planned to use this project for.

**Comment by RotBolt** [comment]
Hi,
I do have plans to support till API 21. I will soon update the library for the same. Currently I am busy with house shifting working, so It could take sometime

**Comment by RotBolt** [comment]
hi @MKevin3 
I have added the support for API 21 in the latest release. Please update the library to latest version
Thanks

Feel free to open the issue if its still causing the issue for API below 24
